# Generated by Django 6.0.4 on 2026-05-25 15:40

import gestion.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_role_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=100, validators=[gestion.validators.validar_nombre]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[gestion.validators.validar_solo_numeros]),
        ),
        migrations.AlterField(
            model_name='detalleorden',
            name='cantidad',
            field=models.PositiveIntegerField(validators=[gestion.validators.validar_cantidad]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(max_length=100, validators=[gestion.validators.validar_nombre]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[gestion.validators.validar_solo_numeros]),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='capacidad',
            field=models.PositiveIntegerField(validators=[gestion.validators.validar_capacidad_mesa]),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='numero_mesa',
            field=models.PositiveIntegerField(unique=True, validators=[gestion.validators.validar_numero_mesa]),
        ),
        migrations.AlterField(
            model_name='plato',
            name='nombre_plato',
            field=models.CharField(max_length=100, validators=[gestion.validators.validar_nombre]),
        ),
        migrations.AlterField(
            model_name='plato',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[gestion.validators.validar_precio]),
        ),
    ]
